### ISSUE TITLE
join taz coords for B_id and egress trips

### ISSUE THREAD

**Issue by bricegnichols** [psrc/fast-trips-validation#3]
currently we merge for access trips, but we need to do the same for egress trips too:
# Join again with TAZ since most A_id walk_access trips are TAZ

taz = pd.read_csv(r'R:\FastTrips\network_draft1.9\taz_coords.txt')

chosenpaths_links_with_observed = pd.merge(chosenpaths_links_with_observed,taz,left_on='A_id',right_on='taz',how='left')

**Comment by bhargavasana** [comment]
Done
